### ISSUE TITLE
Please update the testnet leaderboard for Julia-Ju-Ju, following the accepted PRs

### ISSUE THREAD

**Issue by Julia-Ju-Ju** [desmos-labs/primer#198]
Thank you!

**Comment by RiccardoM** [comment]
The Scoreboard is updated automatically. You can see that you got 160 tokens on Phase 3 here: https://primer.desmos.network/scoreboard/scoreboard.html

Also, please note the initial warning :
> Currently, for Phase 3 the validators rewards are **not shown**. We are working to make sure those rewards are computed properly so that might take a little more time than usual. Please stay tuned on our social networks to know when they will be displayed.
