### ISSUE TITLE
Error: failed to load Store: wanted to load target 257300 but only found up to 250000

### ISSUE THREAD

**Issue by Julia-Ju-Ju** [desmos-labs/primer#229]
My validator stopped and jailed, with the following error in logs, restart don't fix the issue

desmosd[20276]: I[2020-05-15|15:18:10.949] starting ABCI with Tendermint               module=main
desmosd[20276]: failed to load Store: wanted to load target 257300 but only found up to 250000

there is enough disk space. the clean DB and restart don't help.

Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M   13M  786M   2% /run
/dev/sda2       195G   36G  150G  20% /

**Comment by kwunyeung** [comment]
@Julia-Ju-Ju this is weird. For "clean DB", do you mean you had run `desmosd unsafe-reset-all`? Can you confirm that you are using the same software version and genesis file stated [here](https://primer.desmos.network/phase-4/update-node.html)? There is another [reference](https://github.com/desmos-labs/morpheus) of the information you can cross check with.
