### ISSUE TITLE
Determine validators rewards

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/primer#238]
Currently we're giving validators 250 DSM upon validating during an entire Primer Phase. Should we increment this number?

**Comment by kwunyeung** [comment]
@RiccardoM I had a discussion with @terencesflam and we will continue the same way of distributing the DSM to validators in the same way as Phase 4 in each phrase until mainnet.

https://medium.com/desmosnetwork/invest-in-desmos-invest-by-validating-e70907be87db

The max for each validator is 6000 in each phase.
